# Dependencies
markdown:            kramdown
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               "lsqboy`s"
tagline:             "学习笔记"
description:         "大浪淘金"
url:                 /
baseurl:             /
gems: [jekyll-paginate]
paginate:            10

# About/contact
author:
  name:              lsqboy
  github:            lsqboy
  disqus:            lsqboy
  duoshuo:           lsqboy-jekyll
  weibo:             lsqboy


# redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough"]

# Gems
gems: [jekyll-paginate]

google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal